version: "3.8"

services:
  app:
    image: bao_cao_su_co
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./tai_lieu
        target: /app/tai_lieu